// DO NOT MODIFY BY HAND
// This file was generated by src/build/generate-tests.ts

import { join } from "node:path"
import { test } from "test-framework"
import { verifyInterpreterAndCompiler } from "test/verify.ts"
import logic from "./output/main.thy.ts"

test("dependencies verify", async () => {
  await verifyInterpreterAndCompiler({
    inputDir: join(__dirname, "input"),
    logic: logic,
    outputDir: join(__dirname, "output"),
    expectedValue: 5
,
  })
})
