import { checkExampleProgramTokens, testTokenizer } from "./test-helper"
import {
  tConstDeclAssign,
  tEndString,
  tEndStringInterpolation,
  tStartString,
  tStartStringInterpolation,
  tStatementTerminator,
  tStringText,
  tValueIdentifier,
} from "./token-type"

testTokenizer("should tokenize simple one-line strings correctly", async () => {
  await checkExampleProgramTokens("strings/one-line/simple.thy", [
    [tValueIdentifier, "print"],
    tStartString,
    tEndString,
    tStatementTerminator,
    [tValueIdentifier, "print"],
    tStartString,
    [tStringText, "himom"],
    tEndString,
    tStatementTerminator,
    tStatementTerminator,
  ])
})

testTokenizer(
  "should tokenize one-line strings with escapes correctly",
  async () => {
    await checkExampleProgramTokens("strings/one-line/escapes.thy", [
      [tValueIdentifier, "print"],
      tStartString,
      [tStringText, 'Some \\"tea\\" for you?'],
      tEndString,
      tStatementTerminator,
      [tValueIdentifier, "print"],
      tStartString,
      [tStringText, "like \\.name\\."],
      tEndString,
      tStatementTerminator,
      tStatementTerminator,
    ])
  },
)

testTokenizer(
  "should tokenize one-line strings with interpolations correctly",
  async () => {
    await checkExampleProgramTokens("strings/one-line/interpolation.thy", [
      [tValueIdentifier, "name1"],
      tConstDeclAssign,
      [tValueIdentifier, "def"],
      tStartString,
      tStringText,
      tEndString,
      tStatementTerminator,
      [tValueIdentifier, "print"],
      tStartString,
      tStartStringInterpolation,
      [tValueIdentifier, "name1"],
      tEndStringInterpolation,
      tEndString,
      tStatementTerminator,
      [tValueIdentifier, "print"],
      tStartString,
      [tStringText, "Greetings, "],
      tStartStringInterpolation,
      [tValueIdentifier, "name1"],
      tEndStringInterpolation,
      [tStringText, "!"],
      tEndString,
      tStatementTerminator,
      [tValueIdentifier, "name2"],
      tConstDeclAssign,
      [tValueIdentifier, "def"],
      tStartString,
      tStringText,
      tEndString,
      tStatementTerminator,
      [tValueIdentifier, "print"],
      tStartString,
      [tStringText, "both "],
      tStartStringInterpolation,
      [tValueIdentifier, "name1"],
      tEndStringInterpolation,
      [tStringText, " and "],
      tStartStringInterpolation,
      [tValueIdentifier, "name2"],
      tEndStringInterpolation,
      tEndString,
      tStatementTerminator,
      tStatementTerminator,
    ])
  },
)

testTokenizer(
  "should tokenize one-line strings with tricky interpolation-like stuff correctly",
  async () => {
    await checkExampleProgramTokens(
      "strings/one-line/interpolation-tripping.thy",
      [
        [tValueIdentifier, "print"],
        tStartString,
        [tStringText, "Just a period."],
        tEndString,
        tStatementTerminator,
        [tValueIdentifier, "print"],
        tStartString,
        [tStringText, "Not. interpolation."],
        tEndString,
        tStatementTerminator,
        [tValueIdentifier, "print"],
        tStartString,
        [tStringText, "..."],
        tEndString,
        tStatementTerminator,
        [tValueIdentifier, "print"],
        tStartString,
        [tStringText, ".."],
        tEndString,
        tStatementTerminator,
        [tValueIdentifier, "print"],
        tStartString,
        [tStringText, "."],
        tEndString,
        tStatementTerminator,
        tStatementTerminator,
        [tValueIdentifier, "name"],
        tConstDeclAssign,
        [tValueIdentifier, "def"],
        tStartString,
        tStringText,
        tEndString,
        tStatementTerminator,
        [tValueIdentifier, "print"],
        tStartString,
        [tStringText, "Sentence. And with "],
        tStartStringInterpolation,
        [tValueIdentifier, "name"],
        tEndStringInterpolation,
        [tStringText, "."],
        tEndString,
        tStatementTerminator,
        tStatementTerminator,
      ],
    )
  },
)
