print "Just a period."
print "Not. interpolation."
print "Not .interpolation."
print "not/../a/../interpolation"
print "......"
print "....."
print "...."
print "..."
print ".."
print "."

name is def "Joe"
print "Sentence. And with ..name..."
