<script> ::= (<statement> (<newline> <statement>)*)?

<statement> ::=
	<static_statement> |
    <declaration> |
    <control_flow_statement> |
    <complex_expression>

<block> ::= <indent> (<statement> (<newline> <statement>)*)? <outdent>

<scoped_value_identifier> ::= <value_identifier> ("." <value_identifier>)*

<value_identifier> ::= [a-z] ([a-z] | [A-Z])*
<type_identifier> ::= [A-Z] ([a-z] | [A-Z])*

<indent> ::= ">>"
<outdent> ::= "<<"
<newline> ::= "\n"
